famedly/helpcenter

docs/help-center/using-famedly/chats.mdx
Fixes: https://github.com/famedly/product-management/issues/1198
=> chore: fix expert tip

.gitignore, README.md
Just added first information to README.md to enable others to work in this Repo, too.
Plus added swap files to .gitignore
=> chore: Add first info to README.md

i18n/de/code.json, i18n/de/docusaurus-plugin-content-docs/current.json, i18n/de/docusaurus-theme-classic/footer.json, i18n/de/docusaurus-theme-classic/navbar.json
This should fix the german translations
=> fix: german translation

README.md, docs/help-center/using-famedly/qr-verification.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/qr-verification.mdx, i18n/en/code.json, i18n/en/docusaurus-plugin-content-docs/current.json, i18n/en/docusaurus-theme-classic/navbar.json
Fixes https://github.com/famedly/product-management/issues/1241
Would like to have feedback from @nikzen and @rvanwaveren before merging.
@nikzen Do you know if there is anything else needed to make this change deployable? I did run `npm run build` before committing and tested the English and German version.
=> feat: Added instructions for QR-verification

docs/help-center/first-steps/first-login.mdx, docs/help-center/using-famedly/qr-verification.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/first-steps/first-login.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/index.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/qr-verification.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/your-account/account-settings.mdx
=> chore: Corrections for QR verification page

docs/help-center/your-account/account-settings.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/your-account/account-settings.mdx
Closes https://github.com/famedly/product-management/issues/1316
=> feat: Added instructions for screen lock

.github/workflows/deploy-review-app.yml
Closes https://github.com/famedly/product-management/issues/1302
=> feat: Add review app

docs/help-center/first-steps/first-login.mdx, docs/help-center/your-account/account-settings.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/first-steps/first-login.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/your-account/account-settings.mdx
fixes https://github.com/famedly/app/issues/5298
=> feat: Applock is now required on mobile devices without os lock

docs/help-center/your-account/account-settings.mdx, docs/help-center/your-account/encryption-security.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/your-account/account-settings.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/your-account/encryption-security.mdx
Closes https://github.com/famedly/product-management/issues/1449
Hint for review:
It seems the review app (https://helpcenter-pr-54.web-review.famedly.de/) doesn't work when you refresh on a page that isn't home. If you want to test the German version, please change the language while you are on home (Welcome to Famedly).
=> docs: Added password best practices

docs/help-center/using-famedly/messages.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/messages.mdx, src/css/custom.css
Fixes https://github.com/famedly/product-management/issues/1559
=> chore: Added article for copying messages

docs/help-center/first-steps/installation.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/first-steps/installation.mdx
Closes https://github.com/famedly/product-management/issues/1354
=> docs: Add instructions for desktop installation of web app

docs/help-center/first-steps/first-login.mdx, docs/help-center/using-famedly/chats.mdx, docs/help-center/using-famedly/messages.mdx, docs/help-center/your-account/account-settings.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/first-steps/first-login.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/audio-video.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/chats.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/messages.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/qr-verification.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/share-files.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/your-account/account-settings.mdx
Closes https://github.com/famedly/product-management/issues/1541
=> docs: Add help center changes for the new presences feature

docs/help-center/using-famedly/share-files.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/share-files.mdx
Also moves the drag and drop box to be desktop specific.
fixes https://github.com/famedly/app/issues/5407
=> Add instructions for copy and paste

docs/help-center/first-steps/first-login.mdx, docs/help-center/using-famedly/qr-verification.mdx, docs/help-center/your-account/troubleshoot.mdx, docusaurus.config.js, i18n/de/docusaurus-plugin-content-docs/current/help-center/first-steps/first-login.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/messages.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/your-account/troubleshoot.mdx, package-lock.json, package.json
This upgrades to docusaurus 3. More information: https://docusaurus.io/docs/migration/v3
=> chore: upgrade to docusaurus 3

docusaurus.config.js
Closes: https://github.com/famedly/product-management/issues/1493
=> chore: update algolia credentials

docs/help-center/using-famedly/messages.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/messages.mdx
Closes: https://github.com/famedly/product-management/issues/1494
=> Fix markdown

docs/help-center/your-account/account-settings.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/your-account/account-settings.mdx
Closes https://github.com/famedly/product-management/issues/1551
=> Add description how to use do not disturb mode

docs/help-center/your-account/account-settings.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/your-account/account-settings.mdx
Fixed the rebase, including changes of the profile settings again.
Closes https://github.com/famedly/product-management/issues/1708
=> fix: Rebase override changes fixed

docs/help-center/using-famedly/chats.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/chats.mdx
Found that small change locally on my PC and thought it was still worth pushing
=> chore: Add information that inactive chat will appear again when clicked away

docs/help-center/using-famedly/advanced-features.mdx
This adds advanced features to the helpcenter
=> feat: add advanced features

i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/audio-video.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/chats.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/share-files.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/your-account/troubleshoot.mdx
Closes https://github.com/famedly/product-management/issues/1857
=> chore: Fix adressing failures in German translation

package-lock.json, package.json
Seems they need to be updated altogether so dependabot PRs will always fail on CI
=> chore: Update docusaurus plugins

docs/help-center/tim-features/approval-list.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/tim-features/approval-list.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/tim-features/contact-organizations.mdx
According to fix in https://github.com/famedly/app/pull/5809
=> chore: adjust approval list add user via user id last step

docs/help-center/using-famedly/chats.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/chats.mdx
Closes https://github.com/famedly/product-management/issues/2204
=> chore: Update description of status

docs/help-center/tim-features/contact-organizations.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/tim-features/contact-organizations.mdx
Closes https://github.com/famedly/product-management/issues/2263
=> docs: Update send requests to contact points

docs/help-center/using-famedly/chats.mdx, docs/help-center/your-account/account-settings.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/chats.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/your-account/account-settings.mdx
Add steps to add/edit/remove a status message and refine description of status in chats
Closes https://github.com/famedly/product-management/issues/2247
=> docs: Add steps to add/edit/remove a status message

docs/help-center/first-steps/first-login.mdx, docs/help-center/first-steps/installation.mdx, docs/help-center/tim-features/administration.mdx, docs/help-center/tim-features/approval-list.mdx, docs/help-center/tim-features/contact-organizations.mdx, docs/help-center/tim-features/login.mdx, docs/help-center/tim-features/use-ehba.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/first-steps/first-login.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/first-steps/installation.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/tim-features/administration.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/tim-features/approval-list.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/tim-features/contact-organizations.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/tim-features/login.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/tim-features/use-ehba.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/login.mdx
Depends on Changes in https://github.com/famedly/helpcenter/pull/137 Please do not merge before those changes are applied! Will make the PR draft although it's ready for review just in case.
Closes https://github.com/famedly/product-management/issues/2127
=> Add TIM login instructions + unify translation of Login

docs/help-center/tim-features/reset-password.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/tim-features/reset-password.mdx
Closes https://github.com/famedly/product-management/issues/2150
=> docs: Add instructions for resetting password in zitadel

docs/help-center/using-famedly/messages.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/messages.mdx
Closes https://github.com/famedly/product-management/issues/2391
=> docs: Add instructions on using the emoji picker on web

docs/help-center/tim-features/use-ehba.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/tim-features/use-ehba.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/messages.mdx
Closes https://github.com/famedly/product-management/issues/2362
=> docs: Add instructions to use eHBA reader app with Famedly Web or mxid

docs/help-center/tim-features/reset-password.mdx, docs/help-center/using-famedly/messages.mdx, docs/help-center/using-famedly/share-files.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/tim-features/reset-password.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/messages.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/share-files.mdx, src/css/custom.css
Closes https://github.com/famedly/product-management/issues/2361
=> docs: Add instructions for hover message context menu usage

docs/help-center/using-famedly/audio-video.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/audio-video.mdx
Closes https://github.com/famedly/product-management/issues/2448
=> docs: Update voice recording instructions

docs/help-center/your-account/account-settings.mdx, i18n/de/docusaurus-plugin-content-docs/current/help-center/your-account/account-settings.mdx
closes #https://github.com/famedly/product-management/issues/2417
This is part of https://github.com/famedly/app/pull/6096 PR. Please DON'T MERGE IT UNTIL THE FEATURE PR IS MERGED.
=> Add help center article for chat-settings setting menu
